### ISSUE TITLE
cant make

### ISSUE THREAD

**Issue by DrOllyGomez** [jts/bri#1]
Folks
Followed instructions in README, I obtained the following..... (see below)
Any help gratefully received.
Mike

==========================================================
make HTSDIR=/home/mike.harbour/nanopolish/htslibcc -o src/bri_index.o -c -O3 -std=c99 -fsigned-char -D_FILE_OFFSET_BITS=64 -g  -I/home/mike.harbour/nanopolish/htslib/ -fPIC src/bri_index.c
cc -o src/bri_main.o -c -O3 -std=c99 -fsigned-char -D_FILE_OFFSET_BITS=64 -g  -I/home/mike.harbour/nanopolish/htslib/ -fPIC src/bri_main.c
cc -o src/bri_test.o -c -O3 -std=c99 -fsigned-char -D_FILE_OFFSET_BITS=64 -g  -I/home/mike.harbour/nanopolish/htslib/ -fPIC src/bri_test.c
cc -o src/bri_get.o -c -O3 -std=c99 -fsigned-char -D_FILE_OFFSET_BITS=64 -g  -I/home/mike.harbour/nanopolish/htslib/ -fPIC src/bri_get.c
cc -o bri -O3 -std=c99 -fsigned-char -D_FILE_OFFSET_BITS=64 -g  -I/home/mike.harbour/nanopolish/htslib/ -fPIC src/bri_index.o src/bri_main.o src/bri_test.o src/bri_get.o -lpthread -lz /home/mike.harbour/nanopolish/htslib/libhts.a
/home/mike.harbour/nanopolish/htslib/libhts.a(bgzf.o): In function `mt_destroy':
/home/mike.harbour/nanopolish/htslib/bgzf.c:1284: undefined reference to `pthread_join'
/home/mike.harbour/nanopolish/htslib/libhts.a(bgzf.o): In function `bgzf_write_init':
/home/mike.harbour/nanopolish/htslib/bgzf.c:262: undefined reference to `deflateInit2_'
/home/mike.harbour/nanopolish/htslib/libhts.a(bgzf.o): In function `bgzf_uncompress':
/home/mike.harbour/nanopolish/htslib/bgzf.c:456: undefined reference to `inflateInit2_'
/home/mike.harbour/nanopolish/htslib/bgzf.c:464: undefined reference to `inflate'
/home/mike.harbour/nanopolish/htslib/bgzf.c:469: undefined reference to `inflateEnd'
/home/mike.harbour/nanopolish/htslib/bgzf.c:477: undefined reference to `inflateEnd'
/home/mike.harbour/nanopolish/htslib/libhts.a(bgzf.o): In function `bgzf_thread_pool':
/home/mike.harbour/nanopolish/htslib/bgzf.c:1247: undefined reference to `pthread_create'
/home/mike.harbour/nanopolish/htslib/libhts.a(bgzf.o): In function `inflate_gzip_block':
/home/mike.harbour/nanopolish/htslib/bgzf.c:520: undefined reference to `inflate'
/home/mike.harbour/nanopolish/htslib/libhts.a(bgzf.o): In function `bgzf_open':
/home/mike.harbour/nanopolish/htslib/bgzf.c:289: undefined reference to `compressBound'
/home/mike.harbour/nanopolish/htslib/libhts.a(bgzf.o): In function `bgzf_dopen':
/home/mike.harbour/nanopolish/htslib/bgzf.c:312: undefined reference to `compressBound'
/home/mike.harbour/nanopolish/htslib/libhts.a(bgzf.o): In function `bgzf_hopen':
/home/mike.harbour/nanopolish/htslib/bgzf.c:335: undefined reference to `compressBound'
/home/mike.harbour/nanopolish/htslib/libhts.a(bgzf.o): In function `bgzf_compress':
/home/mike.harbour/nanopolish/htslib/bgzf.c:363: undefined reference to `deflateInit2_'
/home/mike.harbour/nanopolish/htslib/bgzf.c:371: undefined reference to `deflate'
/home/mike.harbour/nanopolish/htslib/bgzf.c:378: undefined reference to `deflateEnd'
/home/mike.harbour/nanopolish/htslib/bgzf.c:390: undefined reference to `crc32'
/home/mike.harbour/nanopolish/htslib/bgzf.c:390: undefined reference to `crc32'
/home/mike.harbour/nanopolish/htslib/libhts.a(bgzf.o): In function `bgzf_gzip_compress':
/home/mike.harbour/nanopolish/htslib/bgzf.c:405: undefined reference to `deflate'
/home/mike.harbour/nanopolish/htslib/libhts.a(bgzf.o): In function `bgzf_read_block':
/home/mike.harbour/nanopolish/htslib/bgzf.c:815: undefined reference to `inflateInit2_'
/home/mike.harbour/nanopolish/htslib/libhts.a(bgzf.o): In function `bgzf_close':
/home/mike.harbour/nanopolish/htslib/bgzf.c:1495: undefined reference to `deflateEnd'
/home/mike.harbour/nanopolish/htslib/bgzf.c:1494: undefined reference to `inflateEnd'
/home/mike.harbour/nanopolish/htslib/libhts.a(hts.o): In function `decompress_peek':
/home/mike.harbour/nanopolish/htslib/hts.c:139: undefined reference to `inflateInit2_'
/home/mike.harbour/nanopolish/htslib/hts.c:142: undefined reference to `inflate'
/home/mike.harbour/nanopolish/htslib/hts.c:145: undefined reference to `inflateEnd'
/home/mike.harbour/nanopolish/htslib/hts.c:145: undefined reference to `inflateEnd'
/home/mike.harbour/nanopolish/htslib/libhts.a(thread_pool.o): In function `hts_tpool_init':
/home/mike.harbour/nanopolish/htslib/thread_pool.c:681: undefined reference to `pthread_mutexattr_init'
/home/mike.harbour/nanopolish/htslib/thread_pool.c:682: undefined reference to `pthread_mutexattr_settype'
/home/mike.harbour/nanopolish/htslib/thread_pool.c:684: undefined reference to `pthread_mutexattr_destroy'
/home/mike.harbour/nanopolish/htslib/thread_pool.c:698: undefined reference to `pthread_create'
/home/mike.harbour/nanopolish/htslib/libhts.a(thread_pool.o): In function `hts_tpool_destroy':
/home/mike.harbour/nanopolish/htslib/thread_pool.c:948: undefined reference to `pthread_join'
/home/mike.harbour/nanopolish/htslib/libhts.a(thread_pool.o): In function `hts_tpool_kill':
/home/mike.harbour/nanopolish/htslib/thread_pool.c:974: undefined reference to `pthread_kill'
/home/mike.harbour/nanopolish/htslib/libhts.a(cram_io.o): In function `zlib_mem_deflate':
/home/mike.harbour/nanopolish/htslib/cram/cram_io.c:815: undefined reference to `deflateInit2_'
/home/mike.harbour/nanopolish/htslib/cram/cram_io.c:829: undefined reference to `deflate'
/home/mike.harbour/nanopolish/htslib/cram/cram_io.c:836: undefined reference to `deflate'
/home/mike.harbour/nanopolish/htslib/cram/cram_io.c:841: undefined reference to `deflateEnd'
/home/mike.harbour/nanopolish/htslib/libhts.a(cram_io.o): In function `itf8_decode_crc':
/home/mike.harbour/nanopolish/htslib/cram/cram_io.c:222: undefined reference to `crc32'
/home/mike.harbour/nanopolish/htslib/cram/cram_io.c:233: undefined reference to `crc32'
/home/mike.harbour/nanopolish/htslib/cram/cram_io.c:207: undefined reference to `crc32'
/home/mike.harbour/nanopolish/htslib/cram/cram_io.c:214: undefined reference to `crc32'
/home/mike.harbour/nanopolish/htslib/cram/cram_io.c:201: undefined reference to `crc32'
/home/mike.harbour/nanopolish/htslib/libhts.a(cram_io.o):/home/mike.harbour/nanopolish/htslib/cram/cram_io.c:645: more undefined references to `crc32' follow
/home/mike.harbour/nanopolish/htslib/libhts.a(cram_io.o): In function `zlib_mem_inflate':
/home/mike.harbour/nanopolish/htslib/cram/cram_io.c:751: undefined reference to `inflateInit2_'
/home/mike.harbour/nanopolish/htslib/cram/cram_io.c:764: undefined reference to `inflate'
/home/mike.harbour/nanopolish/htslib/cram/cram_io.c:784: undefined reference to `inflateEnd'
/home/mike.harbour/nanopolish/htslib/libhts.a(cram_io.o): In function `cram_read_block':
/home/mike.harbour/nanopolish/htslib/cram/cram_io.c:979: undefined reference to `crc32'
/home/mike.harbour/nanopolish/htslib/cram/cram_io.c:981: undefined reference to `crc32'
/home/mike.harbour/nanopolish/htslib/cram/cram_io.c:1015: undefined reference to `crc32'
/home/mike.harbour/nanopolish/htslib/libhts.a(cram_io.o): In function `cram_write_block':
/home/mike.harbour/nanopolish/htslib/cram/cram_io.c:1089: undefined reference to `crc32'
/home/mike.harbour/nanopolish/htslib/cram/cram_io.c:1094: undefined reference to `crc32'
/home/mike.harbour/nanopolish/htslib/libhts.a(cram_io.o):/home/mike.harbour/nanopolish/htslib/cram/cram_io.c:3156: more undefined references to `crc32' follow
/home/mike.harbour/nanopolish/htslib/libhts.a(zfio.o): In function `zfputs':
/home/mike.harbour/nanopolish/htslib/cram/zfio.c:81: undefined reference to `gzputs'
/home/mike.harbour/nanopolish/htslib/libhts.a(zfio.o): In function `zfpeek':
/home/mike.harbour/nanopolish/htslib/cram/zfio.c:98: undefined reference to `gzungetc'
/home/mike.harbour/nanopolish/htslib/cram/zfio.c:96: undefined reference to `gzgetc'
/home/mike.harbour/nanopolish/htslib/libhts.a(zfio.o): In function `zfopen':
/home/mike.harbour/nanopolish/htslib/cram/zfio.c:137: undefined reference to `gzopen'
/home/mike.harbour/nanopolish/htslib/cram/zfio.c:142: undefined reference to `gzopen'
/home/mike.harbour/nanopolish/htslib/libhts.a(zfio.o): In function `zfclose':
/home/mike.harbour/nanopolish/htslib/cram/zfio.c:151: undefined reference to `gzclose'
/home/mike.harbour/nanopolish/htslib/libhts.a(zfio.o): In function `zfgets':
/home/mike.harbour/nanopolish/htslib/cram/zfio.c:70: undefined reference to `gzgets'
/home/mike.harbour/nanopolish/htslib/libhts.a(zfio.o): In function `zfeof':
/home/mike.harbour/nanopolish/htslib/cram/zfio.c:106: undefined reference to `gzeof'
collect2: error: ld returned 1 exit status
Makefile:46: recipe for target 'bri' failed
make: *** [bri] Error 1
mike.harbour@bioinf3:~/bri/bri$ ls

**Comment by jts** [comment]
Did you use the same compiler/machine to build `libhts` as `bri`?

**Comment by DrOllyGomez** [comment]
I believe so, yes.

**Comment by DrOllyGomez** [comment]
1)When trying to make bri, I pointed at the htslib found in nanopolish's install directory. 
2)It's possible/probable that I ran the make of nanopolish with the "HDF5=noinstall, EIGEN=noinstall or HTS=noinstall" since I share the machine with others and there was a comment on the nanopolish page about  "Some users however may want to use system-wide versions of the libraries".
Is this relevant/connected/the cause? Many thanks in advance

**Comment by jts** [comment]
It looks like libhts compiled, since you get symbol undefined errors instead of a file-not-found error. The symbols that it is complaining about should be provided by `-lz` and `-lpthread` so I'm not sure what the problem is.

**Comment by jts** [comment]
Can you try running this command:

```
cc -o bri -O3 -std=c99 -fsigned-char -D_FILE_OFFSET_BITS=64 -g -I/home/mike.harbour/nanopolish/htslib/ -fPIC src/bri_index.o src/bri_main.o src/bri_test.o src/bri_get.o /home/mike.harbour/nanopolish/htslib/libhts.a -lpthread -lz
```

**Comment by DrOllyGomez** [comment]
ran that command, completed ok, no errors reported. I have an executable bri now, which gives....
prompt:~/bri/bri$ ./bri 
[bri] usage bri <subprogram> [...]
prompt:~/bri/bri$

...will test it.... but... Many Thanks!

**Comment by DrOllyGomez** [comment]
er... there was some strange strikethroughs added there that shouldnt have been, that wasnt me, it was github :)

**Comment by jts** [comment]
Thanks, the problem was the order that the libraries were linked in. I have fixed this in the Makefile.
